services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile.api1
    ports:
      - "3000:3000"

  api2:
    build:
      context: .
      dockerfile: Dockerfile.api2
    ports:
      - "3001:3001"
